name: Main workflow

permissions:
  contents: read
  packages: write

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  snap-build:
    uses: ./.github/workflows/snap-build.yaml
  snap-publish:
    needs: [snap-build]
    uses: ./.github/workflows/snap-publish.yaml
    secrets: inherit
    if: always()
